apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev # Deploys to QA namespace
resources:
  - ../../base
replicas:
  - name: app-deployment
    count: 1
images:
  - name: app-image
    newName: sandeshs/app
    digest: sha256:395ea99714ef0aa2be24f2173d6530d5b71d6706aa6e132c392fc897174db905
