apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: qa            # Deploys to QA namespace
resources:
  - ../../base
replicas:
  - name: app-deployment
    count: 1

images:
  - name: app-image
    newName: sandeshs/app
    newTag:
